### ISSUE TITLE
请问下，数据库操作有带事务吗？浏览了下，好像没看到事务相关操作

### ISSUE THREAD

**Issue by GuoCeng** [bullteam/zeus-admin#14]
如题所示，浏览代码过程中，没有看到事务相关操作，想问下有没有事务管理，有的话，能跟我说下，在哪里吗？我去学习下

**Comment by wutongci** [comment]
暂时并没有加事务这块，这个系统主要做后台权限管理，只有权限、用户的几个功能的CRUD，不存在高并发场景，所以暂时没考虑事务这块，后续会补上。
